spring:
  application:
    name: clase3
  datasource:
    url: jdbc:mysql://localhost:3306/BD2_Li
    username: cibertec
    password: cibertec
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
